name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # Only run on master branch as requested
  workflow_dispatch:    # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job - reuses the web build logic from build.yml
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Create firebase_options.dart
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID_WEB: ${{ secrets.FIREBASE_APP_ID_WEB }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          cat > lib/firebase_options.dart << EOF
          // File generated by GitHub Actions from secrets
          // DO NOT EDIT - This file is auto-generated in CI/CD

          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart' show kIsWeb;

          class DefaultFirebaseOptions {
            // Only web is configured here. Native platforms (Android/iOS) should use
            // their platform-specific configuration files (e.g., google-services.json).
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                return web;
              }
              throw UnsupportedError(
                'DefaultFirebaseOptions.currentPlatform is only supported on web.\n'
                'Use Firebase.initializeApp() without options on Android/iOS.',
              );
            }

            static const FirebaseOptions web = FirebaseOptions(
              apiKey: '$FIREBASE_API_KEY',
              appId: '$FIREBASE_APP_ID_WEB',
              messagingSenderId: '$FIREBASE_MESSAGING_SENDER_ID',
              projectId: '$FIREBASE_PROJECT_ID',
              authDomain: '$FIREBASE_AUTH_DOMAIN',
              storageBucket: '$FIREBASE_STORAGE_BUCKET',
            );
          }
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build web for GitHub Pages
        run: flutter build web --release --base-href "/routine_timer/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

  # Deployment job
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4