name: Preview Deploy (Firebase Hosting)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write
  deployments: write

jobs:
  build-and-deploy:
    name: Build web and deploy preview
    runs-on: ubuntu-latest
    # Do not attempt deploys for forked PRs (secrets are not available to forks)
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    concurrency:
      group: firebase-preview-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version: latest

      - name: Enable web and install dependencies
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting preview channel
        if: ${{ secrets.FIREBASE_PROJECT_ID != '' && secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: 'pr-${{ github.event.pull_request.number }}'
          # Quote to avoid YAML parsing ambiguity
          expires: '7d'
          entryPoint: '.'

      - name: Skip deploy (missing secrets)
        if: ${{ !(secrets.FIREBASE_PROJECT_ID != '' && secrets.FIREBASE_SERVICE_ACCOUNT != '') }}
        run: echo "Skipping Firebase deploy because FIREBASE_PROJECT_ID or FIREBASE_SERVICE_ACCOUNT is missing."
