name: Tests & Coverage

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests with coverage
      run: flutter test --coverage

    - name: Install lcov
      if: github.event_name == 'pull_request'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lcov

    - name: Normalize coverage file paths
      if: github.event_name == 'pull_request'
      run: |
        # Convert Windows-style backslashes to Unix-style forward slashes
        sed -i 's/\\/\//g' coverage/lcov.info
        echo "Coverage file paths normalized"

    - name: Verify coverage file exists
      if: github.event_name == 'pull_request'
      run: |
        if [ ! -f coverage/lcov.info ]; then
          echo "Error: coverage/lcov.info not found!"
          exit 1
        fi
        echo "Coverage file size: $(wc -c < coverage/lcov.info) bytes"
        echo "Coverage file lines: $(wc -l < coverage/lcov.info) lines"

    - name: Extract coverage percentage
      if: github.event_name == 'pull_request'
      id: coverage
      run: |
        COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep "lines" | awk '{print $2}')
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE"
        
    - name: Generate detailed coverage list
      if: github.event_name == 'pull_request'
      id: detailed
      run: |
        # Use genhtml to generate proper per-file coverage first
        genhtml coverage/lcov.info -o coverage/html --quiet
        # Extract coverage summary from genhtml output for better detail
        lcov --summary coverage/lcov.info 2>&1 | tee coverage-summary.txt
        # Parse the lcov.info file directly for per-file statistics
        echo "Detailed Per-File Coverage:" > coverage-list.txt
        echo "" >> coverage-list.txt
        
        # Parse lcov.info to extract per-file coverage
        awk '
          /^SF:/ { file = substr($0, 4); gsub(/^lib\//, "", file) }
          /^LH:/ { hit = substr($0, 4) }
          /^LF:/ { total = substr($0, 4) }
          /^end_of_record/ { 
            if (total > 0) {
              pct = (hit / total) * 100
              printf "%-50s %6.1f%% (%3d/%3d lines)\n", file, pct, hit, total
            }
          }
        ' coverage/lcov.info | sort -k2 -rn >> coverage-list.txt
        
        echo "Detailed coverage report generated"
        cat coverage-list.txt

    - name: Generate HTML coverage report  
      if: github.event_name == 'pull_request'
      run: |
        # HTML report already generated in previous step
        echo "HTML coverage report available at coverage/html/index.html"

    - name: Upload coverage artifacts
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage/lcov.info
          coverage-list.txt
          coverage/html/
        retention-days: 30

    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const coverage = '${{ steps.coverage.outputs.percentage }}';
          
          // Read the coverage list file that was generated in the previous step
          const lcovOutput = fs.readFileSync('coverage-list.txt', 'utf-8');
          
          // Parse coverage percentage
          const coverageNum = parseFloat(coverage);
          const emoji = coverageNum >= 80 ? '✅' : coverageNum >= 60 ? '⚠️' : '❌';
          
          const comment = `## ${emoji} Test Coverage Report
          
          **Overall Coverage: ${coverage}**
          
          <details>
          <summary>📊 Detailed Coverage</summary>
          
          \`\`\`
          ${lcovOutput}
          \`\`\`
          
          </details>
          
          ---
          
          📦 **Coverage artifacts available**: Download the full coverage report (including HTML) from the [Actions artifacts](https://github.com/${ context.repo.owner }/${ context.repo.repo }/actions/runs/${ context.runId }).
          
          *Coverage threshold: ✅ ≥80% | ⚠️ ≥60% | ❌ <60%*
          `;
          
          // Find existing coverage comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Test Coverage Report')
          );
          
          // Update or create comment
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          }

